[package]
name = "zakki"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
anyhow = "1.0.82"
base64 = "0.22.1"
cbc = { version = "0.1.2", features = ["std"] }
clap = { version = "4.5.4", features = ["derive"] }
derive_builder = "0.20.0"
dialoguer = "0.11.0"
indoc = "2.0.5"
latex2mathml = "0.2.3"
pathdiff = "0.2.1"
pulldown-cmark = { version = "0.11.0", features = ["simd"] }
rand = "0.8.5"
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.116"
sha2 = "0.10.8"
syntastica = "0.4.1"
syntastica-parsers = { version = "0.4.1", features = ["all"] }
syntastica-themes = "0.4.1"
yaml-rust2 = "0.8.0"
